name: checkkawkaw
description: CheckKawKaw - Scam Detection App
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  flutter_foreground_task: ^9.1.0
  record: ^6.1.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_contacts: ^1.1.7
  flutter_local_notifications: ^17.1.2
  file_picker: ^10.3.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true # Generate for Android
  image_path: "C:/Users/jjcha/Downloads/Screenshot__587_-removebg-preview.png" # Path to your icon image
